version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fileservice-postgres
    environment:
      POSTGRES_DB: fileservice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fileservice-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fileservice-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fileservice_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    networks:
      - fileservice-network

volumes:
  postgres_data:
    driver: local

networks:
  fileservice-network:
    driver: bridge

