spring:
  application:
    name: file-upload-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

# File Storage Configuration
file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}
  max-size: 10485760 # 10MB in bytes
  allowed-extensions: jpg,jpeg,png,gif,webp,bmp

# Image Processing Configuration
image:
  thumbnail:
    width: 200
    height: 200
  resize:
    max-width: 1920
    max-height: 1080

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Logging
logging:
  level:
    root: INFO
    com.fileservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
