spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Production file storage (using temp directory on Heroku)
file:
  upload-dir: ${FILE_UPLOAD_DIR:/tmp/uploads}

logging:
  level:
    com.fileservice: INFO
    org.springframework.web: WARN
