spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.shopping: DEBUG
    org.springframework.web: DEBUG
